export default {
  'mode': 'dev',
  'role': 'staff',
  'permissions': {
    'access_backstage': true,
    'spawn_backstage': false,
    'access_tunnel': true,
    'broadcast': true,
    'moderator': true,
    'stage_controls': true
  },
  'mediaSoup': {
    'url': 'wss:\/\/mediasoup.soundstage.fm'
  },
  follows: [],
  mutelist: [],
  blocklist: [],
  'highFidelity': {
    'url': 'api-pro.highfidelity.com'
  },
  'videos': [{
    'url': 'https://assets.soundstage.fm/vr/Default.mp4',
    'label': 'Default'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Intro.mp4',
    'label': 'Intro'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Abyss.mp4',
    'label': 'Abyss'
  }, {
    'url': 'https://assets.soundstage.fm/vr/beat-swiper.mp4',
    'label': 'Beat Swiper'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Blue-Beams.mp4',
    'label': 'Blue Beams'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Disco-2.mp4',
    'label': 'Disco'
  }, {
    'url': 'https://assets.soundstage.fm/vr/flamboyant-lines.mp4',
    'label': 'Flamboyant Lines'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Megapixel.mp4',
    'label': 'Megapixel'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Purple-Tunnel.mp4',
    'label': 'Purple Tunnel'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Reactor.mp4',
    'label': 'Reactor'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Retro-1.mp4',
    'label': 'Waves'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Retro-2.mp4',
    'label': 'Retro'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Ring-Pulse.mp4',
    'label': 'Ring Pulse'
  }, {
    'url': 'https://assets.soundstage.fm/vr/split-sphere.mp4',
    'label': 'Split Sphere'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Color-Tiler.mp4',
    'label': 'Tiler'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Cube-Trails.mp4',
    'label': 'Trails'
  }, {
    'url': 'https://assets.soundstage.fm/vr/Ultra.mp4',
    'label': 'Ultra'
  }],
  'hideDefaultPosters': true,
  'posters': [
    {
      'name': 'DOGE-AtomicSwap',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': 3.428,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.mp4'
    }, {
      'name': 'BTC_BlackSwan',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': -5.022,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/BTC_BlackSwan_2.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/BTC_BlackSwan.mp4'
    }, {
      'name': 'CRYPTOWAVES_AtomicSwap',
      'width': 3.15,
      'height': 2,
      'posX': 4.437,
      'posY': 4.450,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_AtomicSwap.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_AtomicSwap.mp4'
    }, {
      'name': 'CRYPTOWAVES_BlackSwan',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': -5.977,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_BlackSwan.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_BlackSwan.mp4'
    }, {
      'name': 'Galaxy_B',
      'width': 2.6,
      'height': 1.6,
      'posX': -5,
      'posY': 1.088,
      'posZ': -2.908,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/Galaxy_B_3.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/Galaxy_B.mp4'
    }, {
      'name': 'CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': -1.380,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal.mp4'
    }, {
      'name': 'CRYPTOWAVES_GenesisBlock',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': 3.316,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_GenesisBlock.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_GenesisBlock.mp4'
    }, {
      'name': 'ETH-GenesisBlock',
      'width': 2,
      'height': 2,
      'posX': -0.911,
      'posY': 4.450,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/ETH-GenesisBlock_2.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/ETH-GenesisBlock.mp4'
    }, {
      'name': 'UNI-EclipseAttack',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': -0.740,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/UNI-EclipseAttack_3.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/UNI-EclipseAttack.mp4'
    }, {
      'name': 'Protons_Neutrons',
      'width': 1,
      'height': 1.6,
      'posX': 5.335,
      'posY': 1.057,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/Protons_Neutrons.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/Protons_Neutrons.mp4'
    },  {
      'name': 'Galaxy_A',
      'width': 1,
      'height': 1.6,
      'posX': 8,
      'posY': 1.057,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/Galaxy_A.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/Galaxy_A.mp4'
    }, {
      'name': 'Electrons',
      'width': 1,
      'height': 1.6,
      'posX': -1.8,
      'posY': 1.088,
      'posZ': -8.545,
      'rotationY': -180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/Electrons.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/Electrons.mp4'
    } , {
      'name': 'Space_&_Time',
      'width': 1,
      'height': 1.6,
      'posX': 9.23,
      'posY': 1.06,
      'posZ': -4.29,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/Space_Time.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/Space_Time.mp4'
    }
  ]
}