export default {
  'event_slug': 'simlink-friends',
  'alias': 'Ara',
  'hideDefaultPosters': true,
  'posters': [
      {
      'name': 'DOGE-AtomicSwap',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': 3.428,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.mp4'
    }, {
      'name': 'BTC_BlackSwan',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': -5.022,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/BTC_BlackSwan_2.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/BTC_BlackSwan.mp4'
    }, {
      'name': 'CRYPTOWAVES_AtomicSwap',
      'width': 3.15,
      'height': 2,
      'posX': 4.437,
      'posY': 4.450,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_AtomicSwap.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_AtomicSwap.mp4'
    }, {
      'name': 'CRYPTOWAVES_BlackSwan',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': -5.977,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_BlackSwan.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_BlackSwan.mp4'
    }, {
      'name': 'CRYPTOWAVES_EclipseAttack',
      'width': 2.6,
      'height': 1.6,
      'posX': -5,
      'posY': 1.088,
      'posZ': -2.908,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EclipseAttack.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EclipseAttack.mp4'
    }, {
      'name': 'CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': -1.380,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_EP_CoverVIP_Deluxe_Journal.mp4'
    }, {
      'name': 'CRYPTOWAVES_GenesisBlock',
      'width': 3.15,
      'height': 2,
      'posX': 9.228,
      'posY': 4.450,
      'posZ': 3.316,
      'rotationY': 90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_GenesisBlock.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/CRYPTOWAVES_GenesisBlock.mp4'
    }, {
      'name': 'ETH-GenesisBlock',
      'width': 2,
      'height': 2,
      'posX': -0.911,
      'posY': 4.450,
      'posZ': -8.545,
      'rotationY': 180,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/ETH-GenesisBlock.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/ETH-GenesisBlock.mp4'
    }, {
      'name': 'UNI-EclipseAttack',
      'width': 2,
      'height': 2,
      'posX': -5,
      'posY': 4.45,
      'posZ': -0.740,
      'rotationY': -90,
      'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/UNI-EclipseAttack_2.png',
      'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/UNI-EclipseAttack.mp4'
    }
  ]
}