export default {
  'event_slug': 'simlink-friends',
  'alias': 'Ara',
  'posters': [{
    'name': 'posterLeft_1280-666',
    'width': 3.84,
    'height': 2,
    'posX': -5,
    'posY': 4.45,
    'posZ': -5.5,
    'rotationY': -90,
    'photo_url': 'https://www.youredm.com/wp-content/uploads/2020/09/Launch-Promo-Landscape.jpg'
  }, {
    'name': 'posterLeft_1-1',
    'width': 2,
    'height': 2,
    'posX': -5,
    'posY': 4.45,
    'posZ': -2,
    'rotationY': -90,
    'photo_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.png',
    'video_url': 'https://assets.soundstage.fm/vr/cryptowaves/DOGE-AtomicSwap.mp4'
  }, {
    'name': 'posterLeft_3-4_1',
    'width': 1.8,
    'height': 2.4,
    'posX': -5,
    'posY': 4.45,
    'posZ': 1.5,
    'rotationY': -90,
    'photo_url': 'https://www.soundstage.fm/storage/photos/NsLIxIB39n6jZHjjVyd70UxEEzwqRM9ErTWgwfDl.jpg'
  }, {
    'name': 'posterLeft_3-4_2',
    'width': 1.8,
    'height': 2.4,
    'posX': -5,
    'posY': 4.45,
    'posZ': 4,
    'rotationY': -90,
    'photo_url': 'https://www.soundstage.fm/storage/photos/ZP5RxnLdO8YcxYNpeeCPYQ4BLRZ0CvnCKV4y2X3V.png'
  }, {
    'name': 'posterCenter_16-9',
    'width': 4.8,
    'height': 2.7,
    'posX': 2,
    'posY': 4.45,
    'posZ': -8.57,
    'rotationY': 180,
    'photo_url': 'https://www.soundstage.fm/storage/photos/ERJGCrb9uJWoqsLK3aFHKJWyu0a6bfBhgZCUqLTa.png'
  },/* {
    'name': 'posterRight_3-1',
    'width': 6,
    'height': 2,
    'posX': 9.23,
    'posY': 4.45,
    'posZ': 0,
    'rotationY': 90,
    'video_url': 'https://assets.soundstage.fm/vr/Ultra.mp4'
  },*/
    {
      'name': 'posterCorner_3-4',
      'width': 3,
      'height': 4,
      'posX': 8.2,
      'posY': 4.3,
      'posZ': -7.5,
      'rotationY': 135,
      'photo_url': 'https://www.soundstage.fm/storage/photos/NsLIxIB39n6jZHjjVyd70UxEEzwqRM9ErTWgwfDl.jpg'
    }]
}